name: All Checks

on: [push, pull_request]

jobs:
  gen-ral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install virtualenv
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: pip install -U -r requirements.txt
      - name: Generate RAL
        run: make ci
      - name: Ensure RAL is consistent with checked-in code
        run: git update-index --refresh && git diff-index --quiet HEAD
      - name: Check format for RAL
        run: cargo fmt --all -- --check
      - name: Run clippy for RAL
        run: cargo clippy -- -D warnings

  build-ral:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature:
          # Individual chips
          - "imxrt1011"
          - "imxrt1015"
          - "imxrt1021"
          - "imxrt1051"
          - "imxrt1052"
          - "imxrt1061"
          - "imxrt1062"
          - "imxrt1064"
          # Chip + other features
          #
          # Only checking this once, assuming that code gen
          # is consistent across all chips.
          - "imxrt1062,rt"
          - "imxrt1062,rtic"
          - "imxrt1062,rt,rtic"
    steps:
    - uses: actions/checkout@v2
    - name: Build for (${{ matrix.feature }}) RAL
      run: cargo build --verbose --features ${{ matrix.feature }}
    - name: Run tests for (${{ matrix.feature }}) RAL
      run: cargo test --verbose --features ${{ matrix.feature }}

  check-imxrtral:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install virtualenv
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: pip install -U -r requirements.txt
    - name: Run Python doctests in imxrtral.py
      run: python -m doctest -v imxrtral.py
